import type { Metadata } from "next";
import { inter, sevillana, dancing_script } from "../fonts";
import layoutStyle from "./layout.module.css";
import "./global.css";

export const metadata: Metadata = {
  title: "Saloon App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  slider,
  details,
  banner,
}: Readonly<{
  children: React.ReactNode;
  slider: React.ReactNode;
  details: React.ReactNode;
  banner: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Applying font classes to the body ensures they affect all routes */}
      <body
        className={`${inter.variable} ${sevillana.variable} ${dancing_script.variable}`}
      >
        <div className="app-wrapper">
          {children}
          {slider}
          <div className={layoutStyle.bannerDetailsContainer}>
            <div className={layoutStyle.detailsCotianer}>{details}</div>
            <div className={layoutStyle.bannerContainer}>{banner}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
